-- MySQL Script generated by MySQL Workbench
-- Sun Apr 24 22:41:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema booking
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema booking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `booking` DEFAULT CHARACTER SET utf8 ;
USE `booking` ;

-- -----------------------------------------------------
-- Table `booking`.`event_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking`.`event_categories` (
  `eventCategoryId` VARCHAR(16) NOT NULL,
  `eventCategoryName` VARCHAR(100) NULL,
  `eventCategoryDescription` VARCHAR(500) NULL,
  PRIMARY KEY (`eventCategoryId`),
  UNIQUE INDEX `eventCategoryId_UNIQUE` (`eventCategoryId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booking`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking`.`booking` (
  `bookingId` VARCHAR(20) NOT NULL,
  `bookingName` VARCHAR(100) NULL,
  `bookingEmail` VARCHAR(45) NULL,
  PRIMARY KEY (`bookingId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booking`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking`.`events` (
  `eventId` VARCHAR(20) NOT NULL,
  `eventStartTime` DATETIME NULL,
  `eventDuration` INT NULL,
  `eventNotes` VARCHAR(500) NULL,
  `eventCategoryId` VARCHAR(16) NOT NULL,
  `bookingId` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`eventId`, `eventCategoryId`),
  INDEX `fk_events_event_categories_idx` (`eventCategoryId` ASC) VISIBLE,
  INDEX `fk_events_booking1_idx` (`bookingId` ASC) VISIBLE,
  CONSTRAINT `fk_events_event_categories`
    FOREIGN KEY (`eventCategoryId`)
    REFERENCES `booking`.`event_categories` (`eventCategoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_booking1`
    FOREIGN KEY (`bookingId`)
    REFERENCES `booking`.`booking` (`bookingId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
