-- MySQL Script generated by MySQL Workbench
-- Tue Apr 26 19:42:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

drop database booking;
CREATE SCHEMA IF NOT EXISTS `booking` DEFAULT CHARACTER SET utf8 ;
USE `booking` ;

-- -----------------------------------------------------
-- Table `mydb`.`eventCategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking`.`eventCategory` (
                                                         `eventCategoryId` INT NOT NULL AUTO_INCREMENT,
                                                         `eventCategoryName` VARCHAR(100) NOT NULL,
    `eventCategoryDescription` VARCHAR(500) NOT NULL,
    `eventDuration` INT NOT NULL,
    PRIMARY KEY (`eventCategoryId`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `booking`.`event` (
                                                 `eventId` INT NOT NULL AUTO_INCREMENT,
                                                 `bookingName` VARCHAR(100) NOT NULL,
    `bookingEmail` VARCHAR(50) NOT NULL,
    `eventStartTime` DATETIME NOT NULL,
    `eventDuration` INT NOT NULL,
    `eventNotes` VARCHAR(500) NULL,
    `eventCategoryId` INT NOT NULL,
    PRIMARY KEY (`eventId`),
    INDEX `fk_event_eventCategory_idx` (`eventCategoryId` ASC) VISIBLE,
    CONSTRAINT `fk_event_eventCategory`
    FOREIGN KEY (`eventCategoryId`)
    REFERENCES `booking`.`eventCategory` (`eventCategoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_events_booking1`
    FOREIGN KEY (`bookingId`)
    REFERENCES `booking`.`booking` (`bookingId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
